#!/bin/python3

import math
import os
import random
import re
import sys


n = int(input())
if n % 2 == 0:                 # if n is even then run the loop
    if n in range(2,6):        # if n is even AND between 2 and 6 print Not Weird
        print("Not Weird")

    elif n in range(6,21):     # if n is even AND between 6 and 21 print Weird
        print("Weird")

    elif n > 20:               # if n is even AND greater than 20 print Not Weird
        print("Not Weird")
else:                          # if n is odd print Weird
    print("Weird")
